export const schools = [
  { id: 1, name: 'Stanford University' },
  { id: 2, name: 'Harvard University' },
  { id: 3, name: 'MIT' },
  { id: 4, name: 'University of California, Berkeley' },
  { id: 5, name: 'Yale University' },
  { id: 6, name: 'Princeton University' },
  { id: 7, name: 'University of Chicago' },
  { id: 8, name: 'Columbia University' },
  { id: 9, name: 'University of Pennsylvania' },
  { id: 10, name: 'Northwestern University' },
  { id: 11, name: 'Duke University' },
  { id: 12, name: 'Dartmouth College' },
  { id: 13, name: 'Brown University' },
  { id: 14, name: 'University of Michigan' },
  { id: 15, name: 'Johns Hopkins University' },
];

export const sports = [
  { id: 1, name: "Men's Tennis" },
  { id: 2, name: "Women's Tennis" },
  { id: 3, name: "Men's Basketball" },
  { id: 4, name: "Women's Basketball" },
  { id: 5, name: "Men's Soccer" },
  { id: 6, name: "Women's Soccer" },
  { id: 7, name: "Men's Swimming" },
  { id: 8, name: "Women's Swimming" },
  { id: 9, name: "Men's Track and Field" },
  { id: 10, name: "Women's Track and Field" },
  { id: 11, name: 'Baseball' },
  { id: 12, name: 'Softball' },
  { id: 13, name: "Men's Volleyball" },
  { id: 14, name: "Women's Volleyball" },
  { id: 15, name: "Men's Golf" },
  { id: 16, name: "Women's Golf" },
];

export const coaches = [
  { id: 1, name: 'Francisco Gonzalez', schoolId: 1, sportId: 1 },
  { id: 2, name: 'Sarah Smith', schoolId: 1, sportId: 2 },
  { id: 3, name: 'John Davis', schoolId: 2, sportId: 3 },
  { id: 4, name: 'Emily Johnson', schoolId: 2, sportId: 4 },
  { id: 5, name: 'Michael Brown', schoolId: 3, sportId: 5 },
  { id: 6, name: 'Jennifer Wilson', schoolId: 3, sportId: 6 },
  { id: 7, name: 'Robert Taylor', schoolId: 4, sportId: 7 },
  { id: 8, name: 'Laura Martinez', schoolId: 4, sportId: 8 },
  { id: 9, name: 'William Anderson', schoolId: 5, sportId: 9 },
  { id: 10, name: 'Elizabeth Thomas', schoolId: 5, sportId: 10 },
  { id: 11, name: 'James Wilson', schoolId: 6, sportId: 11 },
  { id: 12, name: 'Patricia Moore', schoolId: 6, sportId: 12 },
  { id: 13, name: 'Richard Jackson', schoolId: 7, sportId: 13 },
  { id: 14, name: 'Barbara White', schoolId: 7, sportId: 14 },
  { id: 15, name: 'David Harris', schoolId: 8, sportId: 15 },
  { id: 16, name: 'Susan Martin', schoolId: 8, sportId: 16 },
  { id: 17, name: 'Joseph Thompson', schoolId: 9, sportId: 1 },
  { id: 18, name: 'Margaret Garcia', schoolId: 9, sportId: 2 },
  { id: 19, name: 'Charles Martinez', schoolId: 10, sportId: 3 },
  { id: 20, name: 'Nancy Robinson', schoolId: 10, sportId: 4 },
  { id: 21, name: 'Thomas Clark', schoolId: 11, sportId: 5 },
  { id: 22, name: 'Lisa Rodriguez', schoolId: 11, sportId: 6 },
  { id: 23, name: 'Daniel Lewis', schoolId: 12, sportId: 7 },
  { id: 24, name: 'Karen Lee', schoolId: 12, sportId: 8 },
  { id: 25, name: 'Paul Walker', schoolId: 13, sportId: 9 },
  { id: 26, name: 'Betty Hall', schoolId: 13, sportId: 10 },
  { id: 27, name: 'Mark Allen', schoolId: 14, sportId: 11 },
  { id: 28, name: 'Sandra Young', schoolId: 14, sportId: 12 },
  { id: 29, name: 'Donald King', schoolId: 15, sportId: 13 },
  { id: 30, name: 'Dorothy Wright', schoolId: 15, sportId: 14 },
];
